spring:
  profiles:
    active: dev
  # 通过springboot访问本机静态资源
  web:
    resources:
      static-locations:
jwt:
  secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  expiration-milliseconds: 604800000
gateway:
  whitelists: /blog-auth/v3/api-docs, /blog-admin/v3/api-docs, /blog-auth/auth/login, /blog-file/v3/api-docs, /blog-file/upload/**

# 通过springboot访问本机静态资源
